version: '2'

services:
  secmgr:
    build:
      context: .
      args:
        - SP_SAML_ENTITY=http://google.com/enterprise/gsa/T4-KRQHV3XHUQEXY/gsa-actual
        - IDP_SAML_ENTITY=http://google.com/enterprise/gsa/T4-KRQHV3XHUQEXY
        - SEC_MGR_HOST_PORT=localhost:8443
        - ARTIFACT_CONSUMER_URL=http://localhost:8088/sample-sp/saml/sp/SSO
        - AUTH_SITES_FILE_NAME=LDAP_SAML_AuthSites.json
          # - APPLIENCE_ID=T4-KRQHV3XHUQEXY
    image: secmgr:latest
    environment:
      - CATALINA_OPTS=-Dgsa.applianceid=T4-KRQHV3XHUQEXY -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -Djava.security.egd=file:/dev/urandom -Denv=dev -Xms1024M -Xmx2048M -XX:PermSize=256M -XX:MaxPermSize=768m
    ports:
      - 8443:8443
      - 8080:8080
      - 5006:5006
    depends_on:
      - openldap

  openldap:
    build: ./openldap_sample_img
    image: openldap
    ports:
      - 389:389

  sample-client:
    build:
      ./sample_sp_for_secmgr
    image: sample_sp_for_secmgr
    ports:
      - 8088:8088
    depends_on:
      - secmgr

